"""Create complete SMS Control Tower schema

Revision ID: 53d6fd907b29
Revises: 
Create Date: 2025-09-02 16:24:36.160437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d6fd907b29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnc_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('normalized_phone', sa.String(), nullable=False),
    sa.Column('list_source', sa.String(), nullable=False),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('registered_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dnc_list'))
    )
    op.create_index(op.f('ix_dnc_list_id'), 'dnc_list', ['id'], unique=False)
    op.create_index(op.f('ix_dnc_list_normalized_phone'), 'dnc_list', ['normalized_phone'], unique=True)
    op.create_index(op.f('ix_dnc_list_phone_number'), 'dnc_list', ['phone_number'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('default_timezone', sa.String(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(), nullable=True),
    sa.Column('quiet_hours_end', sa.String(), nullable=True),
    sa.Column('default_rate_limit_mps', sa.Integer(), nullable=True),
    sa.Column('daily_message_limit', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_phone_numbers', sa.Integer(), nullable=True),
    sa.Column('max_templates', sa.Integer(), nullable=True),
    sa.Column('compliance_settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('webhook_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_webhook_logs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_logs'))
    )
    op.create_index(op.f('ix_webhook_logs_created_at'), 'webhook_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_org_id'), 'webhook_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_processed'), 'webhook_logs', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_logs_provider'), 'webhook_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_webhook_logs_webhook_type'), 'webhook_logs', ['webhook_type'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target_criteria', sa.JSON(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_mps', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('respect_quiet_hours', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('template_rotation', sa.Boolean(), nullable=True),
    sa.Column('selected_templates', sa.JSON(), nullable=True),
    sa.Column('phone_number_pool', sa.JSON(), nullable=True),
    sa.Column('rotate_numbers', sa.Boolean(), nullable=True),
    sa.Column('total_targets', sa.Integer(), nullable=True),
    sa.Column('targets_queued', sa.Integer(), nullable=True),
    sa.Column('targets_sent', sa.Integer(), nullable=True),
    sa.Column('targets_delivered', sa.Integer(), nullable=True),
    sa.Column('targets_failed', sa.Integer(), nullable=True),
    sa.Column('targets_replied', sa.Integer(), nullable=True),
    sa.Column('targets_opted_out', sa.Integer(), nullable=True),
    sa.Column('delivery_rate', sa.Float(), nullable=True),
    sa.Column('reply_rate', sa.Float(), nullable=True),
    sa.Column('opt_out_rate', sa.Float(), nullable=True),
    sa.Column('cost_per_send', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('compliance_checked', sa.Boolean(), nullable=True),
    sa.Column('compliance_issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_campaigns_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone1', sa.String(), nullable=False),
    sa.Column('phone2', sa.String(), nullable=True),
    sa.Column('phone3', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('acreage', sa.Float(), nullable=True),
    sa.Column('estimated_value', sa.Integer(), nullable=True),
    sa.Column('property_address', sa.String(), nullable=True),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('lead_score', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('consent_status', sa.String(), nullable=True),
    sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_out_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_out_reason', sa.String(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_campaign_id', sa.UUID(), nullable=True),
    sa.Column('total_messages_sent', sa.Integer(), nullable=True),
    sa.Column('total_messages_received', sa.Integer(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversion_event', sa.String(), nullable=True),
    sa.Column('conversion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversion_value', sa.Integer(), nullable=True),
    sa.Column('phone1_valid', sa.Boolean(), nullable=True),
    sa.Column('phone2_valid', sa.Boolean(), nullable=True),
    sa.Column('phone3_valid', sa.Boolean(), nullable=True),
    sa.Column('address_valid', sa.Boolean(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('import_row_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_leads_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leads_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.create_index(op.f('ix_leads_county'), 'leads', ['county'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_first_name'), 'leads', ['first_name'], unique=False)
    op.create_index(op.f('ix_leads_full_name'), 'leads', ['full_name'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_last_name'), 'leads', ['last_name'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_lead_source'), 'leads', ['lead_source'], unique=False)
    op.create_index(op.f('ix_leads_parcel_id'), 'leads', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_leads_phone1'), 'leads', ['phone1'], unique=False)
    op.create_index(op.f('ix_leads_phone2'), 'leads', ['phone2'], unique=False)
    op.create_index(op.f('ix_leads_phone3'), 'leads', ['phone3'], unique=False)
    op.create_index(op.f('ix_leads_property_type'), 'leads', ['property_type'], unique=False)
    op.create_index(op.f('ix_leads_state'), 'leads', ['state'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_zip_code'), 'leads', ['zip_code'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('formatted_number', sa.String(), nullable=False),
    sa.Column('display_number', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_sid', sa.String(), nullable=True),
    sa.Column('messaging_service_sid', sa.String(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('mms_enabled', sa.Boolean(), nullable=True),
    sa.Column('voice_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_message_count', sa.Integer(), nullable=True),
    sa.Column('weekly_message_count', sa.Integer(), nullable=True),
    sa.Column('monthly_message_count', sa.Integer(), nullable=True),
    sa.Column('total_message_count', sa.Integer(), nullable=True),
    sa.Column('rate_limit_mps', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('current_daily_count', sa.Integer(), nullable=True),
    sa.Column('delivery_rate', sa.Float(), nullable=True),
    sa.Column('reply_rate', sa.Float(), nullable=True),
    sa.Column('opt_out_rate', sa.Float(), nullable=True),
    sa.Column('spam_rate', sa.Float(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dedicated', sa.Boolean(), nullable=True),
    sa.Column('assigned_campaigns', sa.JSON(), nullable=True),
    sa.Column('blocked_keywords', sa.JSON(), nullable=True),
    sa.Column('carrier_name', sa.String(), nullable=True),
    sa.Column('carrier_type', sa.String(), nullable=True),
    sa.Column('registered_brand', sa.String(), nullable=True),
    sa.Column('campaign_registry', sa.JSON(), nullable=True),
    sa.Column('acquisition_cost', sa.Float(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('cost_per_message', sa.Float(), nullable=True),
    sa.Column('pool_priority', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('area_code', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acquired_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acquired_by'], ['users.id'], name=op.f('fk_phone_numbers_acquired_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_phone_numbers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers'))
    )
    op.create_index(op.f('ix_phone_numbers_id'), 'phone_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_last_used_at'), 'phone_numbers', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_phone_numbers_organization_id'), 'phone_numbers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_phone_number'), 'phone_numbers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_phone_numbers_provider'), 'phone_numbers', ['provider'], unique=False)
    op.create_index(op.f('ix_phone_numbers_status'), 'phone_numbers', ['status'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('required_variables', sa.JSON(), nullable=True),
    sa.Column('optional_variables', sa.JSON(), nullable=True),
    sa.Column('variable_schema', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('avg_segments', sa.Integer(), nullable=True),
    sa.Column('ab_test_group', sa.String(), nullable=True),
    sa.Column('ab_test_weight', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_templates_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_templates_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_templates_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_language'), 'templates', ['language'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('compliance_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_audit_events_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_audit_events_lead_id_leads')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_events_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_org_id'), 'audit_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_events_phone_number'), 'audit_events', ['phone_number'], unique=False)
    op.create_table('campaign_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('from_phone_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('message_segments', sa.Integer(), nullable=True),
    sa.Column('twilio_message_sid', sa.String(), nullable=True),
    sa.Column('twilio_status', sa.String(), nullable=True),
    sa.Column('twilio_error_code', sa.String(), nullable=True),
    sa.Column('twilio_error_message', sa.String(), nullable=True),
    sa.Column('scheduled_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_targets_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_campaign_targets_lead_id_leads')),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_campaign_targets_template_id_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_targets'))
    )
    op.create_index(op.f('ix_campaign_targets_campaign_id'), 'campaign_targets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_targets_id'), 'campaign_targets', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_targets_lead_id'), 'campaign_targets', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_targets_phone_number'), 'campaign_targets', ['phone_number'], unique=False)
    op.create_index(op.f('ix_campaign_targets_sent_at'), 'campaign_targets', ['sent_at'], unique=False)
    op.create_index(op.f('ix_campaign_targets_status'), 'campaign_targets', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_targets_twilio_message_sid'), 'campaign_targets', ['twilio_message_sid'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('lead_phone', sa.String(), nullable=False),
    sa.Column('our_phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('inbound_messages', sa.Integer(), nullable=True),
    sa.Column('outbound_messages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_conversations_assigned_to_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_conversations_lead_id_leads')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_conversations_lead_phone'), 'conversations', ['lead_phone'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversations_our_phone'), 'conversations', ['our_phone'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_table('lead_phones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('e164', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('consent_status', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('carrier_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_phones_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_phones'))
    )
    op.create_index(op.f('ix_lead_phones_e164'), 'lead_phones', ['e164'], unique=False)
    op.create_index(op.f('ix_lead_phones_id'), 'lead_phones', ['id'], unique=False)
    op.create_index(op.f('ix_lead_phones_lead_id'), 'lead_phones', ['lead_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('to_phone', sa.String(), nullable=False),
    sa.Column('from_phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('twilio_message_sid', sa.String(), nullable=True),
    sa.Column('twilio_status', sa.String(), nullable=True),
    sa.Column('twilio_error_code', sa.String(), nullable=True),
    sa.Column('twilio_error_message', sa.Text(), nullable=True),
    sa.Column('twilio_num_segments', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('media_urls', sa.Text(), nullable=True),
    sa.Column('contains_keywords', sa.String(), nullable=True),
    sa.Column('compliance_action', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_messages_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_messages_lead_id_leads')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_messages_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], name=op.f('fk_messages_parent_message_id_messages')),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_messages_template_id_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_campaign_id'), 'messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_from_phone'), 'messages', ['from_phone'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_template_id'), 'messages', ['template_id'], unique=False)
    op.create_index(op.f('ix_messages_to_phone'), 'messages', ['to_phone'], unique=False)
    op.create_index(op.f('ix_messages_twilio_message_sid'), 'messages', ['twilio_message_sid'], unique=True)
    op.create_table('message_status_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_status_events_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_status_events'))
    )
    op.create_index(op.f('ix_message_status_events_created_at'), 'message_status_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_status_events_id'), 'message_status_events', ['id'], unique=False)
    op.create_index(op.f('ix_message_status_events_message_id'), 'message_status_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_status_events_status'), 'message_status_events', ['status'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('normalized_phone', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('opt_out_message', sa.Text(), nullable=True),
    sa.Column('detected_keywords', sa.String(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('suppressed_campaigns', sa.String(), nullable=True),
    sa.Column('suppressed_from_phones', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('resubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resubscription_method', sa.String(), nullable=True),
    sa.Column('resubscription_notes', sa.Text(), nullable=True),
    sa.Column('compliance_type', sa.String(), nullable=True),
    sa.Column('legal_basis', sa.String(), nullable=True),
    sa.Column('retention_period', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_suppressions_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_suppressions_created_by_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_suppressions_lead_id_leads')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_suppressions_message_id_messages')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_suppressions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_suppressions_processed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppressions'))
    )
    op.create_index(op.f('ix_suppressions_campaign_id'), 'suppressions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_suppressions_created_at'), 'suppressions', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppressions_id'), 'suppressions', ['id'], unique=False)
    op.create_index(op.f('ix_suppressions_lead_id'), 'suppressions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_suppressions_message_id'), 'suppressions', ['message_id'], unique=False)
    op.create_index(op.f('ix_suppressions_normalized_phone'), 'suppressions', ['normalized_phone'], unique=False)
    op.create_index(op.f('ix_suppressions_organization_id'), 'suppressions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_suppressions_phone_number'), 'suppressions', ['phone_number'], unique=False)
    op.create_index(op.f('ix_suppressions_reason'), 'suppressions', ['reason'], unique=False)
    op.create_table('template_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('was_delivered', sa.Boolean(), nullable=True),
    sa.Column('was_replied', sa.Boolean(), nullable=True),
    sa.Column('was_opted_out', sa.Boolean(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('rendered_content', sa.Text(), nullable=True),
    sa.Column('message_segments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_template_usage_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_template_usage_lead_id_leads')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_template_usage_message_id_messages')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_template_usage_organization_id_organizations')),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_template_usage_template_id_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_usage'))
    )
    op.create_index(op.f('ix_template_usage_campaign_id'), 'template_usage', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_template_usage_id'), 'template_usage', ['id'], unique=False)
    op.create_index(op.f('ix_template_usage_lead_id'), 'template_usage', ['lead_id'], unique=False)
    op.create_index(op.f('ix_template_usage_organization_id'), 'template_usage', ['organization_id'], unique=False)
    op.create_index(op.f('ix_template_usage_template_id'), 'template_usage', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_usage_used_at'), 'template_usage', ['used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_usage_used_at'), table_name='template_usage')
    op.drop_index(op.f('ix_template_usage_template_id'), table_name='template_usage')
    op.drop_index(op.f('ix_template_usage_organization_id'), table_name='template_usage')
    op.drop_index(op.f('ix_template_usage_lead_id'), table_name='template_usage')
    op.drop_index(op.f('ix_template_usage_id'), table_name='template_usage')
    op.drop_index(op.f('ix_template_usage_campaign_id'), table_name='template_usage')
    op.drop_table('template_usage')
    op.drop_index(op.f('ix_suppressions_reason'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_phone_number'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_organization_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_normalized_phone'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_message_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_lead_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_created_at'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_campaign_id'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_message_status_events_status'), table_name='message_status_events')
    op.drop_index(op.f('ix_message_status_events_message_id'), table_name='message_status_events')
    op.drop_index(op.f('ix_message_status_events_id'), table_name='message_status_events')
    op.drop_index(op.f('ix_message_status_events_created_at'), table_name='message_status_events')
    op.drop_table('message_status_events')
    op.drop_index(op.f('ix_messages_twilio_message_sid'), table_name='messages')
    op.drop_index(op.f('ix_messages_to_phone'), table_name='messages')
    op.drop_index(op.f('ix_messages_template_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_phone'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_campaign_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_lead_phones_lead_id'), table_name='lead_phones')
    op.drop_index(op.f('ix_lead_phones_id'), table_name='lead_phones')
    op.drop_index(op.f('ix_lead_phones_e164'), table_name='lead_phones')
    op.drop_table('lead_phones')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_our_phone'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_phone'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_campaign_targets_twilio_message_sid'), table_name='campaign_targets')
    op.drop_index(op.f('ix_campaign_targets_status'), table_name='campaign_targets')
    op.drop_index(op.f('ix_campaign_targets_sent_at'), table_name='campaign_targets')
    op.drop_index(op.f('ix_campaign_targets_phone_number'), table_name='campaign_targets')
    op.drop_index(op.f('ix_campaign_targets_lead_id'), table_name='campaign_targets')
    op.drop_index(op.f('ix_campaign_targets_id'), table_name='campaign_targets')
    op.drop_index(op.f('ix_campaign_targets_campaign_id'), table_name='campaign_targets')
    op.drop_table('campaign_targets')
    op.drop_index(op.f('ix_audit_events_phone_number'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_org_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_templates_language'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_phone_numbers_status'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_provider'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_phone_number'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_organization_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_last_used_at'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_leads_zip_code'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_state'), table_name='leads')
    op.drop_index(op.f('ix_leads_property_type'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone3'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone2'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone1'), table_name='leads')
    op.drop_index(op.f('ix_leads_parcel_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_last_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_full_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_first_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_county'), table_name='leads')
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_webhook_logs_webhook_type'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_provider'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_processed'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_org_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_created_at'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_dnc_list_phone_number'), table_name='dnc_list')
    op.drop_index(op.f('ix_dnc_list_normalized_phone'), table_name='dnc_list')
    op.drop_index(op.f('ix_dnc_list_id'), table_name='dnc_list')
    op.drop_table('dnc_list')
    # ### end Alembic commands ###
